# Generated by Django 4.2 on 2023-04-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Position', models.CharField(max_length=50)),
                ('Office', models.CharField(max_length=50)),
                ('age', models.IntegerField(null=True)),
                ('Startdate', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'Add employee',
            },
        ),
        migrations.AlterModelTable(
            name='student',
            table='Student',
        ),
    ]
